/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rez.iems.frames;

import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import rez.iems.connectionprovider.getcon;
import rez.iems.info.customerentities;
import rez.iems.info.customerinfo;

/**
 *
 * @author ahmed
 */
public class clientregistration extends javax.swing.JFrame {

    /**
     * Creates new form clientregistration
     */
    customerentities cus = new customerentities();
    public clientregistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cpasstxt = new rojerusan.RSPasswordTextPlaceHolder();
        passtxt = new rojerusan.RSPasswordTextPlaceHolder();
        signinbtn = new rojerusan.RSMaterialButtonRectangle();
        emailtxt = new app.bolivia.swing.JCTextField();
        addresstxt = new app.bolivia.swing.JCTextField();
        nidtxt = new app.bolivia.swing.JCTextField();
        nametxt = new app.bolivia.swing.JCTextField();
        uploadimg = new rojerusan.RSMaterialButtonRectangle();
        showpassword = new rojerusan.RSMaterialButtonRectangle();
        signupbtn = new rojerusan.RSMaterialButtonRectangle();
        resetbtn = new rojerusan.RSMaterialButtonRectangle();
        phonenotxt = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        imgpreview = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 180, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 251, 235));
        jLabel2.setText("Already Joined Us!!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 251, 235));
        jLabel1.setText("WELCOME!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 251, 235));
        jLabel4.setText("Events planning and managing with IEMS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 251, 235));
        jLabel3.setText("Save your time and Simplify your....");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        cpasstxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 153, 153)));
        cpasstxt.setForeground(new java.awt.Color(0, 0, 0));
        cpasstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpasstxt.setEchoChar('\u2022');
        cpasstxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cpasstxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        cpasstxt.setPhColor(new java.awt.Color(0, 0, 0));
        cpasstxt.setPlaceholder("Confirm Password.....");
        jPanel1.add(cpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 330, 40));

        passtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 153, 153)));
        passtxt.setForeground(new java.awt.Color(0, 0, 0));
        passtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passtxt.setEchoChar('\u2022');
        passtxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        passtxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        passtxt.setPhColor(new java.awt.Color(0, 0, 0));
        passtxt.setPlaceholder("Password.....");
        jPanel1.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 330, 40));

        signinbtn.setBackground(new java.awt.Color(188, 226, 158));
        signinbtn.setForeground(new java.awt.Color(51, 51, 51));
        signinbtn.setText("SIGN IN");
        signinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 140, 50));

        emailtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 153, 153)));
        emailtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailtxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        emailtxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        emailtxt.setPlaceholder("Your email..");
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 330, 40));

        addresstxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 153, 153)));
        addresstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addresstxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        addresstxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        addresstxt.setPlaceholder("Your Address...");
        jPanel1.add(addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 330, 40));

        nidtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 153, 153)));
        nidtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nidtxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nidtxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        nidtxt.setPlaceholder("Your NID no");
        jPanel1.add(nidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 330, 40));

        nametxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 153, 153)));
        nametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nametxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nametxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        nametxt.setPlaceholder("Your Name.");
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 330, 40));

        uploadimg.setBackground(new java.awt.Color(188, 226, 158));
        uploadimg.setForeground(new java.awt.Color(51, 51, 51));
        uploadimg.setText("Upload Image");
        uploadimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadimgActionPerformed(evt);
            }
        });
        jPanel1.add(uploadimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 170, 40));

        showpassword.setBackground(new java.awt.Color(188, 226, 158));
        showpassword.setForeground(new java.awt.Color(51, 51, 51));
        showpassword.setText("SHOW PASSWORD");
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 150, 40));

        signupbtn.setBackground(new java.awt.Color(188, 226, 158));
        signupbtn.setForeground(new java.awt.Color(51, 51, 51));
        signupbtn.setText("SIGN UP");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 140, 40));

        resetbtn.setBackground(new java.awt.Color(188, 226, 158));
        resetbtn.setForeground(new java.awt.Color(51, 51, 51));
        resetbtn.setText("RESET");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 140, 40));

        phonenotxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 153, 153)));
        phonenotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phonenotxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        phonenotxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        phonenotxt.setPlaceholder("Your Phone No..");
        jPanel1.add(phonenotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 330, 40));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 251, 235));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Profile Picture Preview");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, 20));

        imgpreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgpreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/icons8-add-image-64.png"))); // NOI18N
        imgpreview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(imgpreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 320, 240));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/icons8-cancel-25.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uploadimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadimgActionPerformed
        // TODO add your handling code here:
                 JFileChooser ch = new JFileChooser();
                 ch.setCurrentDirectory(new File(System.getProperty("user.home")));
                 FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image","jpg","jpeg","JPG","JPEG","png","PNG");
                 ch.addChoosableFileFilter(filter);
               int check =  ch.showSaveDialog(null);
               if(check==JFileChooser.APPROVE_OPTION){
                 File fl = ch.getSelectedFile();
                 
                 String url = fl.getAbsolutePath();
                 Icon icon = new ImageIcon(url);
                 int w = icon.getIconWidth();
                 int h = icon.getIconHeight();
                 String filename = fl.getName();
                 if((w==320&&h==240)&& (filename.endsWith(".JPG")||filename.endsWith(".jpg")||filename.endsWith(".jpeg")||filename.endsWith(".JPEG")||filename.endsWith(".png")||filename.endsWith(".PNG")))
                 { 
                     cus.setImg(url);
                     imgpreview.setIcon(icon);
                 }
                 else 
                 {
                       Thread th=new Thread(){
                         @Override
                         public void run(){
                    try{
                           
                        loading ff = new loading();
                        ff.setVisible(true);
                            Thread.sleep(500);
                        ff.setVisible(false);
                            invalidimg fr = new invalidimg();
                            fr.setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
                 }
                 
               }
               else {
                   
                 
               }
    }//GEN-LAST:event_uploadimgActionPerformed
     public int x =0;
    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        
         if(x == 0)
         {
             passtxt.setEchoChar((char)0);
             cpasstxt.setEchoChar((char)0);
             x=1;
         }
         else 
         {
             passtxt.setEchoChar('\u2022');
             cpasstxt.setEchoChar('\u2022');
             x=0;   
         }
         
        
    }//GEN-LAST:event_showpasswordActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        String name=nametxt.getText();
        String email = emailtxt.getText();
        String contactno = phonenotxt.getText();
        String address = addresstxt.getText();
        String pass = passtxt.getText();
        String cpass = cpasstxt.getText();
        String nid = nidtxt.getText();
        if(pass.equals(cpass)==false)
        {
            new confpass().setVisible(true);
        }
        else {
            cus.setName(name);
            cus.setEmail(email);
            cus.setAddress(address);
            cus.setCnid(nid);
            cus.setContactno(contactno);
            cus.setPass(pass);
            if(name.equals("")!=true && email.equals("")!=true && cus.getImg().equals("")!=true && address.equals("")!=true && contactno.equals("")!=true && pass.equals("")!=true && cpass.equals("")!=true){
                customerinfo cusin = new customerinfo(getcon.getConnection());
                customerentities c = cusin.getcustomer(email, pass);
                if(c == null)
                {
                     boolean b = cusin.savecustomerinfo(cus);
                     if(b==true)
                     {
                          Thread th=new Thread(){
                @Override
                public void run(){
                    try{
                           
                        loading ff = new loading();
                        ff.setVisible(true);
                            Thread.sleep(500);
                        ff.setVisible(false);
                            successfullregistration fr = new successfullregistration();
                            fr.setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
             this.setVisible(false);
        Thread t=new Thread(){
                @Override
                public void run(){
                    try{
                           
                            Thread.sleep(200);
                          login fr = new login();
                            fr.setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };t.start();
                     }
                }
                else 
                {
                 Thread th=new Thread(){
                @Override
                public void run(){
                    try{
                           
                        loading ff = new loading();
                        ff.setVisible(true);
                            Thread.sleep(500);
                        ff.setVisible(false);
                            exist fr = new exist();
                            fr.setVisible(true);
                            emailtxt.setText("");
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
                }
            }
           
            
        }
       
    }//GEN-LAST:event_signupbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        nametxt.setText("");
        emailtxt.setText("");
        phonenotxt.setText("");
        passtxt.setText("");
        cpasstxt.setText("");
        addresstxt.setText("");
        nidtxt.setText("");
        String url = "C:\\Users\\ahmed\\OneDrive\\Documents\\NetBeansProjects\\IEM_Systems\\src\\rez\\iems\\figures\\icons8-add-image-64.png";
        Icon icon = new ImageIcon(url);
        imgpreview.setIcon(icon);
    }//GEN-LAST:event_resetbtnActionPerformed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_closeMousePressed

    private void signinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       Thread th=new Thread(){
                @Override
                public void run(){
                    try{
                           
                            Thread.sleep(200);
                          login fr = new login();
                            fr.setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
    }//GEN-LAST:event_signinbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientregistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField addresstxt;
    private javax.swing.JLabel close;
    private rojerusan.RSPasswordTextPlaceHolder cpasstxt;
    private app.bolivia.swing.JCTextField emailtxt;
    private javax.swing.JLabel imgpreview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private app.bolivia.swing.JCTextField nametxt;
    private app.bolivia.swing.JCTextField nidtxt;
    private rojerusan.RSPasswordTextPlaceHolder passtxt;
    private app.bolivia.swing.JCTextField phonenotxt;
    private rojerusan.RSMaterialButtonRectangle resetbtn;
    private rojerusan.RSMaterialButtonRectangle showpassword;
    private rojerusan.RSMaterialButtonRectangle signinbtn;
    private rojerusan.RSMaterialButtonRectangle signupbtn;
    private rojerusan.RSMaterialButtonRectangle uploadimg;
    // End of variables declaration//GEN-END:variables
}
