/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rez.iems.frames;

import rez.iems.connectionprovider.getcon;
import rez.iems.info.vendorentities;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ahmed
 */
public class crevent extends javax.swing.JFrame {

    /**
     * Creates new form crevent
     */
    public crevent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        askingprice = new app.bolivia.swing.JCTextField();
        eid = new app.bolivia.swing.JCTextField();
        name = new app.bolivia.swing.JCTextField();
        section = new app.bolivia.swing.JCTextField();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        back = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 180, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        askingprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        askingprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        askingprice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        askingprice.setPlaceholder("Enter Asking Price");
        jPanel1.add(askingprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 470, 40));

        eid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        eid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        eid.setPlaceholder("Enter Event Id");
        jPanel1.add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 470, 40));

        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        name.setPlaceholder("Enter Event Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 470, 40));

        section.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        section.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        section.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        section.setPlaceholder("Enter Section");
        jPanel1.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 470, 40));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(204, 255, 153));
        rSMaterialButtonRectangle1.setForeground(new java.awt.Color(51, 51, 51));
        rSMaterialButtonRectangle1.setText("ADD");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 200, 40));

        back.setBackground(new java.awt.Color(204, 255, 153));
        back.setForeground(new java.awt.Color(51, 51, 51));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 40));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(204, 255, 153));
        rSMaterialButtonRectangle2.setForeground(new java.awt.Color(51, 51, 51));
        rSMaterialButtonRectangle2.setText("DELETE");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     static public vendorentities ven = login.getven();
     int b=0;
    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        try {
            // TODO add your handling code here:
            String id = eid.getText();
            String nam = name.getText();
            String sec = section.getText();
            String ask = askingprice.getText();
            int code = ven.getCode();
            int ed = Integer.parseInt(id);
            float as = Float.parseFloat(ask);
            String query = "select * from event where eid ='"+ed+"' and code='"+code+"'";
            PreparedStatement psmt=getcon.getConnection().prepareStatement(query);
            ResultSet rs = psmt.executeQuery(query);
            if(rs.next())
            {
                new alreadyexist().setVisible(true);
                
                
            }
            else 
            {
                query = "insert into event(eid,name,code,section,askingprice) values(?,?,?,?,?)";
                psmt=getcon.getConnection().prepareStatement(query);
                psmt.setInt(1,ed);
                psmt.setString(2, nam);
                psmt.setInt(3, code);
                psmt.setString(4, sec);
                psmt.setFloat(5, as);
                psmt.executeUpdate();  
                b=1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(crevent.class.getName()).log(Level.SEVERE, null, ex);
            b=0;
        }
        if(b==1)
        {
            new successfullyupdated().setVisible(true);
        }
        else 
        {
           new updateerror().setVisible(true);
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new editprofileven().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        try {
            // TODO add your handling code here:
            String id = eid.getText();
            String nam = name.getText();
            String sec = section.getText();
            String ask = askingprice.getText();
            int code = ven.getCode();
            int ed = Integer.parseInt(id);
            float as = Float.parseFloat(ask);
            String query = "delete from event where eid ='"+ed+"' and code='"+code+"'";
            PreparedStatement psmt=getcon.getConnection().prepareStatement(query);
            psmt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(crevent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crevent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField askingprice;
    private rojerusan.RSMaterialButtonRectangle back;
    private app.bolivia.swing.JCTextField eid;
    private javax.swing.JPanel jPanel1;
    private app.bolivia.swing.JCTextField name;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private app.bolivia.swing.JCTextField section;
    // End of variables declaration//GEN-END:variables
}
