/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rez.iems.frames;

import rez.iems.connectionprovider.getcon;
import rez.iems.info.customerentities;
import rez.iems.info.customerinfo;
import rez.iems.info.vendorentities;
import rez.iems.info.vendorinfo;

/**
 *
 * @author ahmed
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng1 = new javax.swing.ButtonGroup();
        joinnowpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        joinnowbtn = new rojerusan.RSMaterialButtonRectangle();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bgpanel = new javax.swing.JPanel();
        loginpanel = new javax.swing.JPanel();
        logintxt1 = new javax.swing.JLabel();
        loginfig1 = new javax.swing.JLabel();
        emailtxt = new app.bolivia.swing.JCTextField();
        passtxt = new rojerusan.RSPasswordTextPlaceHolder();
        resetbtn = new rojerusan.RSMaterialButtonRectangle();
        signinbtn = new rojerusan.RSMaterialButtonRectangle();
        logintxt2 = new javax.swing.JLabel();
        vendor = new javax.swing.JRadioButton();
        client = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("login"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        joinnowpanel.setBackground(new java.awt.Color(84, 180, 53));
        joinnowpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 251, 235));
        jLabel3.setText("IEMS");
        joinnowpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 251, 235));
        jLabel2.setText("ENGAGE CONSUMERS.");
        joinnowpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 251, 235));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("saves time for the consumers");
        joinnowpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 240, -1));

        joinnowbtn.setBackground(new java.awt.Color(204, 255, 153));
        joinnowbtn.setForeground(new java.awt.Color(51, 51, 51));
        joinnowbtn.setText("JOIN NOW");
        joinnowbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        joinnowbtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        joinnowbtn.setRippleColor(new java.awt.Color(0, 102, 153));
        joinnowbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinnowbtnActionPerformed(evt);
            }
        });
        joinnowpanel.add(joinnowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, 50));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 251, 235));
        jLabel6.setText("JOIN US");
        joinnowpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 251, 235));
        jLabel7.setText("FOR HIRING EVENT PLANERS AND...");
        joinnowpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 251, 235));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("One of the leading community ");
        joinnowpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 190, 20));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 251, 235));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("for event managers,planners to be hired");
        joinnowpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 240, 20));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/icons8-cancel-25.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        joinnowpanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        getContentPane().add(joinnowpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 540, 670));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("About US");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 30));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contact US");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Serving with pure passion it's our oath © 2023 IEMS. All rights reserved.");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1080, 50));

        bgpanel.setBackground(new java.awt.Color(73, 85, 121));
        bgpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginpanel.setBackground(new java.awt.Color(255, 204, 102));
        loginpanel.setName("loginpanel"); // NOI18N
        loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logintxt1.setBackground(new java.awt.Color(38, 49, 89));
        logintxt1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        logintxt1.setForeground(new java.awt.Color(51, 51, 51));
        logintxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logintxt1.setText("SIGN IN AS");
        loginpanel.add(logintxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 220, -1));

        loginfig1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginfig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/loginpage1.jpg"))); // NOI18N
        loginfig1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginpanel.add(loginfig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 340, 240));

        emailtxt.setBackground(new java.awt.Color(248, 255, 219));
        emailtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(236, 114, 114)));
        emailtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailtxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        emailtxt.setMargin(new java.awt.Insets(3, 10, 3, 6));
        emailtxt.setPhColor(new java.awt.Color(51, 51, 51));
        emailtxt.setPlaceholder("Enter Email");
        loginpanel.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 390, 40));

        passtxt.setBackground(new java.awt.Color(248, 255, 219));
        passtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(236, 114, 114)));
        passtxt.setForeground(new java.awt.Color(0, 0, 0));
        passtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passtxt.setEchoChar('\u2022');
        passtxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        passtxt.setMargin(new java.awt.Insets(3, 10, 3, 6));
        passtxt.setPhColor(new java.awt.Color(51, 51, 51));
        passtxt.setPlaceholder("Enter Password");
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        loginpanel.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 390, 40));

        resetbtn.setBackground(new java.awt.Color(255, 102, 51));
        resetbtn.setText("Reset");
        resetbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetbtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        resetbtn.setRippleColor(new java.awt.Color(0, 102, 153));
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        loginpanel.add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 100, 40));

        signinbtn.setBackground(new java.awt.Color(255, 102, 51));
        signinbtn.setText("SIGN IN");
        signinbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signinbtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        signinbtn.setRippleColor(new java.awt.Color(0, 102, 153));
        signinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtnActionPerformed(evt);
            }
        });
        loginpanel.add(signinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 100, 40));

        logintxt2.setBackground(new java.awt.Color(38, 49, 89));
        logintxt2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        logintxt2.setForeground(new java.awt.Color(51, 51, 51));
        logintxt2.setText("WELCOME BACK");
        loginpanel.add(logintxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 220, -1));

        vendor.setBackground(new java.awt.Color(255, 204, 102));
        btng1.add(vendor);
        vendor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        vendor.setForeground(new java.awt.Color(51, 51, 51));
        vendor.setText("vendor");
        loginpanel.add(vendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        client.setBackground(new java.awt.Color(255, 204, 102));
        btng1.add(client);
        client.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        client.setForeground(new java.awt.Color(51, 51, 51));
        client.setText("client");
        loginpanel.add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        bgpanel.add(loginpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 670));

        getContentPane().add(bgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxtActionPerformed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMousePressed

    private void joinnowbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinnowbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         Thread th=new Thread(){
                @Override
                public void run(){
                    try{
                           
                        loading ff = new loading();
                        ff.setVisible(true);
                            Thread.sleep(500);
                        ff.setVisible(false);
                            registration fr = new registration();
                            fr.setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
        
    }//GEN-LAST:event_joinnowbtnActionPerformed
   static customerentities cus = new customerentities();
   static vendorentities ven = new vendorentities();
    public static int c = 0,v = 0;
    private void signinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtnActionPerformed
        // TODO add your handling code here:
        String email = emailtxt.getText();
        String pass = passtxt.getText();
        
        if(client.isSelected())
        {
            c = 1; v = 0;
         customerinfo cusin= new customerinfo(getcon.getConnection());
         cus = cusin.getcustomer(email, pass);
         if(cus==null)
         {
            
             Thread th=new Thread(){
                @Override
                public void run(){
                    try{
                           
                        loading ff = new loading();
                        ff.setVisible(true);
                            Thread.sleep(500);
                        ff.setVisible(false);
                        new invaliddialog().setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
             
         }
         else {
         
         this.setVisible(false);
         Thread th=new Thread(){
                @Override
                public void run(){
                    try{
                           
                        loading ff = new loading();
                        ff.setVisible(true);
                        Thread.sleep(500);
                        ff.setVisible(false);
                        home fr = new home();
                        fr.setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
         }
        }
        else if(vendor.isSelected())
        {
         v=1; c=0;
         vendorinfo venin= new vendorinfo(getcon.getConnection());
         ven =venin.getvendor(email, pass);
         if(ven==null)
         {
            
             Thread th=new Thread(){
                @Override
                public void run(){
                    try{
                           
                            loading ff = new loading();
                        ff.setVisible(true);
                        Thread.sleep(500);
                        ff.setVisible(false);
                        new invaliddialog().setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
             
         }
         else {
         this.setVisible(false);
         Thread th=new Thread(){
                @Override
                public void run(){
                    try{
                           
                        loading ff = new loading();
                        ff.setVisible(true);
                        Thread.sleep(500);
                        ff.setVisible(false);
                        vendorhome fr = new vendorhome();
                        fr.setVisible(true);
                        }catch(Exception e){
                        e.printStackTrace();
                    }}
                
            };th.start();
         }
        }
        else 
        {
             c = 0;
             v = 0;
        }
    }//GEN-LAST:event_signinbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
          // TODO add your handling code here:
          emailtxt.setText("");
          passtxt.setText("");
          
        
    }//GEN-LAST:event_resetbtnActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new Contactus().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new abt().setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked
   static public customerentities getcus()
    {
        if(c==1)
        {
            return cus;
        }
        else 
        {
            return null;
        }
    }
   static public vendorentities getven()
    {
        if(v==1)
        {
            return ven;
        }
        else return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgpanel;
    private javax.swing.ButtonGroup btng1;
    private javax.swing.JRadioButton client;
    private javax.swing.JLabel close;
    private app.bolivia.swing.JCTextField emailtxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonRectangle joinnowbtn;
    private javax.swing.JPanel joinnowpanel;
    private javax.swing.JLabel loginfig1;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JLabel logintxt1;
    private javax.swing.JLabel logintxt2;
    private rojerusan.RSPasswordTextPlaceHolder passtxt;
    private rojerusan.RSMaterialButtonRectangle resetbtn;
    private rojerusan.RSMaterialButtonRectangle signinbtn;
    private javax.swing.JRadioButton vendor;
    // End of variables declaration//GEN-END:variables
}
