/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rez.iems.frames;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import rez.iems.connectionprovider.getcon;

/**
 *
 * @author ahmed
 */
public class pfven extends javax.swing.JFrame {

    /**
     * Creates new form pfven
     */
    public pfven(int code) {
        initComponents();
       int cd=code;
        try {
            String query ="select * from vendor where code='"+cd+"'";
            PreparedStatement pst = getcon.getConnection().prepareStatement(query);
            ResultSet rs = pst.executeQuery(query);
            while(rs.next())
            {
                name.setText(rs.getString("name"));
                phnno.setText(rs.getString("contactno"));
                bin.setText(rs.getString("bin"));
                rt.setText(Float.toString(rs.getFloat("response")));
                Icon icon = new ImageIcon(rs.getString("profilepic"));
                pic.setImagen(icon);
            }
        } catch (SQLException ex) {
            Logger.getLogger(pfven.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialShadowRectangle1 = new efectos.MaterialShadowRectangle();
        jPanel1 = new javax.swing.JPanel();
        pic = new rojerusan.RSPanelImage();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rt = new app.bolivia.swing.JCTextField();
        name = new app.bolivia.swing.JCTextField();
        phnno = new app.bolivia.swing.JCTextField();
        bin = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 480));
        setUndecorated(true);
        setSize(new java.awt.Dimension(920, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout picLayout = new javax.swing.GroupLayout(pic);
        pic.setLayout(picLayout);
        picLayout.setHorizontalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        picLayout.setVerticalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 240));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/icons8-cancel-25.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Rating :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 70, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 50, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Phone No :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 80, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("BIN :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 70, 30));

        rt.setEditable(false);
        rt.setBackground(new java.awt.Color(204, 255, 255));
        rt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        rt.setForeground(new java.awt.Color(51, 51, 51));
        rt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 330, -1));

        name.setEditable(false);
        name.setBackground(new java.awt.Color(204, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 330, -1));

        phnno.setEditable(false);
        phnno.setBackground(new java.awt.Color(204, 255, 255));
        phnno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        phnno.setForeground(new java.awt.Color(51, 51, 51));
        phnno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phnno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(phnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 330, -1));

        bin.setEditable(false);
        bin.setBackground(new java.awt.Color(204, 255, 255));
        bin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        bin.setForeground(new java.awt.Color(51, 51, 51));
        bin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(bin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 330, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pfven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pfven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pfven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pfven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pfven(-1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField bin;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private efectos.MaterialShadowRectangle materialShadowRectangle1;
    private app.bolivia.swing.JCTextField name;
    private app.bolivia.swing.JCTextField phnno;
    private rojerusan.RSPanelImage pic;
    private app.bolivia.swing.JCTextField rt;
    // End of variables declaration//GEN-END:variables
}
