/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rez.iems.frames;

/**
 *
 * @author ahmed
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionpanel = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vendorbtn = new rojerusan.RSMaterialButtonRectangle();
        clientbtn = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("registration"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        selectionpanel.setBackground(new java.awt.Color(84, 180, 53));
        selectionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/icons8-cancel-25.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        selectionpanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 251, 235));
        jLabel1.setText("SIGN UP AS");
        selectionpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 296, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/icons8-user-male-100.png"))); // NOI18N
        selectionpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 100, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/icons8-human-100.png"))); // NOI18N
        selectionpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 100, 100));

        vendorbtn.setBackground(new java.awt.Color(204, 255, 102));
        vendorbtn.setForeground(new java.awt.Color(51, 51, 51));
        vendorbtn.setText("Vendor");
        vendorbtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        vendorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorbtnActionPerformed(evt);
            }
        });
        selectionpanel.add(vendorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 170, 40));

        clientbtn.setBackground(new java.awt.Color(204, 255, 102));
        clientbtn.setForeground(new java.awt.Color(51, 51, 51));
        clientbtn.setText("Client");
        clientbtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        clientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientbtnActionPerformed(evt);
            }
        });
        selectionpanel.add(clientbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(selectionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(selectionpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMousePressed

    private void clientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientbtnActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       new clientregistration().setVisible(true);
    
    }//GEN-LAST:event_clientbtnActionPerformed

    private void vendorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new vendorregistration().setVisible(true);
    }//GEN-LAST:event_vendorbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle clientbtn;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel selectionpanel;
    private rojerusan.RSMaterialButtonRectangle vendorbtn;
    // End of variables declaration//GEN-END:variables
}
