/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rez.iems.frames;

/**
 *
 * @author ahmed
 */


import rez.iems.info.vendorentities;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import rez.iems.connectionprovider.getcon;
public class showevents extends javax.swing.JFrame {

    /**
     * Creates new form showevents
     */
    static vendorentities ven = login.getven();
    
    public showevents() {
        initComponents();
        try {
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            int rows = model.getRowCount();
            for(int i=rows-1;i>=0;i--)
            {
                model.removeRow(i);
            }
            String q ;
            int cd = ven.getCode();
            q = "select * from event where code ='"+cd+"'";
            PreparedStatement pst = getcon.getConnection().prepareStatement(q);
            ResultSet rs = pst.executeQuery(q);
            while(rs.next()){
            int id = rs.getInt("eid");
            String name = rs.getString("name");
            float price = rs.getFloat("askingprice");
            q = "select count(cnid) as cnt from adds where eid = '"+id+"'";
            pst = getcon.getConnection().prepareStatement(q);
            ResultSet res = pst.executeQuery(q);
            int cnt=0;
            while(res.next()){
             cnt = res.getInt("cnt");
            }
            Object[] obj = {id,name,price,cnt};
            model = (DefaultTableModel) table.getModel();
            model.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(showevents.class.getName()).log(Level.SEVERE, null, ex);
        }
        com.addItem("All");
        try {
            int cd = ven.getCode();
            String query="select distinct(event.section) from  event where   code ='"+cd+"'";
            PreparedStatement psmt = getcon.getConnection().prepareStatement(query);
            ResultSet rs = psmt.executeQuery(query);
            while(rs.next()){
                String name = rs.getString("section");
                com.addItem(name);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new rojeru_san.complementos.RSTableMetro();
        com = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        showme = new rojerusan.RSMaterialButtonRectangle();
        close = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 180, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Search By Event Type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        table.setForeground(new java.awt.Color(51, 51, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event ID", "Event Name", "Asking Amount", "No of Sales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setColorBackgoundHead(new java.awt.Color(255, 204, 102));
        table.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        table.setColorBordeHead(new java.awt.Color(102, 102, 102));
        table.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        table.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        table.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        table.setColorForegroundHead(new java.awt.Color(0, 51, 51));
        table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        table.setGridColor(new java.awt.Color(102, 102, 102));
        table.setRowHeight(40);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setHeaderValue("Event ID");
            table.getColumnModel().getColumn(1).setHeaderValue("Event Name");
            table.getColumnModel().getColumn(2).setHeaderValue("Asking Amount");
            table.getColumnModel().getColumn(3).setHeaderValue("No of Sales");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 960, 190));

        com.setBackground(new java.awt.Color(255, 204, 102));
        com.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        com.setForeground(new java.awt.Color(51, 51, 51));
        com.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comActionPerformed(evt);
            }
        });
        jPanel1.add(com, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 140, 160, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("Events Author By You");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        showme.setBackground(new java.awt.Color(255, 204, 102));
        showme.setForeground(new java.awt.Color(51, 51, 51));
        showme.setText("SHOW ME");
        showme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showmeActionPerformed(evt);
            }
        });
        jPanel1.add(showme, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 160, 40));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rez/iems/figures/icons8-cancel-25.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 204, 102));
        rSMaterialButtonRectangle1.setForeground(new java.awt.Color(51, 51, 51));
        rSMaterialButtonRectangle1.setText("Back");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comActionPerformed

    private void showmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showmeActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            int rows = model.getRowCount();
            for(int i=rows-1;i>=0;i--)
            {
                model.removeRow(i);
            }
            
            String sel = com.getSelectedItem().toString();
            String q ;
            int cd = ven.getCode();
            
            if(sel.equals("All"))
            {
                q = "select * from event where code ='"+cd+"'";
            }
            else
            {
                q = "select * from event where code='"+cd+"' and section='"+sel+"'";
            }
            PreparedStatement pst = getcon.getConnection().prepareStatement(q);
            ResultSet rs = pst.executeQuery(q);
            while(rs.next()){
            int id = rs.getInt("eid");
            String name = rs.getString("name");
            float price = rs.getFloat("askingprice");
            q = "select count(cnid) as cnt from adds where eid = '"+id+"'";
            pst = getcon.getConnection().prepareStatement(q);
            ResultSet res = pst.executeQuery(q);
            int cnt=0;
            while(res.next()){
             cnt = res.getInt("cnt");
            }
            Object[] obj = {id,name,price,cnt};
            model = (DefaultTableModel) table.getModel();
            model.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(showevents.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_showmeActionPerformed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeMousePressed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new vendorprofile().setVisible(true);
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showevents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JComboBox<String> com;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle showme;
    private rojeru_san.complementos.RSTableMetro table;
    // End of variables declaration//GEN-END:variables
}
